import { catalogImages } from "@/utils/catalog-assets";
import { Category, Product, Testimonial } from "@/utils/types";

export const categories: Category[] = [
  { id: "cat-1", name: "Smart Home", slug: "smart-home", description: "Automation essentials for modern homes." },
  { id: "cat-2", name: "Car Essentials", slug: "car-essentials", description: "Travel-ready cleaning and mounting gadgets." },
  { id: "cat-3", name: "Workspace", slug: "workspace", description: "Compact upgrades for desks and study setups." },
  { id: "cat-4", name: "Lifestyle Tech", slug: "lifestyle-tech", description: "Everyday utility products with smart features." },
  { id: "cat-5", name: "Wellness & Style", slug: "wellness-style", description: "Beauty, self-care, and stylish daily companions." }
];

export const products: Product[] = [
  {
    id: "prd-1",
    slug: "motion-sensor-led-night-light",
    title: "Motion Sensor LED Night Light",
    description: "Rechargeable warm-light puck with 110° PIR coverage, USB-C charging, and 30K lumen output.",
    price: 799,
    comparePrice: 1299,
    stock: 120,
    category: "Smart Home",
    images: [catalogImages.nightLight],
    rating: 4.7,
    vendor: "EZY Smart Shop",
    badge: "Best Seller",
    specifications: ["110° motion sensor", "USB-C recharge (30+ day runtime)", "Magnetic + adhesive mount"],
    shippingDetails: ["Ships in 24 hours", "Free delivery above Rs 999", "7-day replacement", "₹50 packaging fee for express"]
  },
  {
    id: "prd-2",
    slug: "3-in-1-wireless-charging-station",
    title: "3-in-1 Wireless Charging Station",
    description: "Fast 15W Qi dock with dedicated Apple Watch puck, silicone cradle, and foldable phone stand.",
    price: 2499,
    comparePrice: 3499,
    stock: 60,
    category: "Workspace",
    images: [catalogImages.chargingStation],
    rating: 4.8,
    vendor: "EZY Smart Shop",
    badge: "Trending",
    specifications: ["15W USB-C PD input", "Dedicated watch charger", "Anti-slip silicone pad"],
    shippingDetails: ["Ships in 24 hours", "COD available", "1-year warranty", "₹99 white-label packaging"]
  },
  {
    id: "prd-3",
    slug: "portable-car-vacuum-cleaner",
    title: "Portable Car Vacuum Cleaner",
    description: "120W high-vacuum motor with HEPA filter, LED crevice nozzle, and cord-free USB-C recharge.",
    price: 1599,
    comparePrice: 2299,
    stock: 85,
    category: "Car Essentials",
    images: [catalogImages.carVacuum],
    rating: 4.5,
    vendor: "EZY Smart Shop",
    specifications: ["120W brushless motor", "Cyclonic HEPA filter", "3 nozzle heads + LED work light"],
    shippingDetails: ["Ships in 48 hours", "Free delivery", "7-day replacement", "₹30 for rural districts"]
  },
  {
    id: "prd-4",
    slug: "magnetic-car-phone-holder",
    title: "Magnetic Car Phone Holder",
    description: "N52 magnets with 360° swivel, leather-textured clamp, and dashboard/vent adapters.",
    price: 699,
    comparePrice: 999,
    stock: 200,
    category: "Car Essentials",
    images: [catalogImages.phoneHolder],
    rating: 4.4,
    vendor: "EZY Smart Shop",
    specifications: ["N52 magnetic disc", "Vent and dash mounting legs", "360° ball-joint swivel"],
    shippingDetails: ["Same-day dispatch", "COD available", "Easy returns"]
  },
  {
    id: "prd-5",
    slug: "electric-lint-remover",
    title: "Electric Lint Remover",
    description: "USB-C rechargeable lint shaver with stainless steel blades, dust cup, and dual-speed control.",
    price: 999,
    comparePrice: 1499,
    stock: 140,
    category: "Lifestyle Tech",
    images: [catalogImages.lintRemover],
    rating: 4.6,
    vendor: "EZY Smart Shop",
    specifications: ["Dual-speed blades", "Detachable dust cup", "USB-C charging with 500mAh battery"],
    shippingDetails: ["Ships in 24 hours", "Free exchange", "7-day support"]
  },
  {
    id: "prd-6",
    slug: "rgb-led-light-strip",
    title: "RGB LED Light Strip",
    description: "5m smart strip with 16M colors, music-sync mode, app control, and adhesive backing.",
    price: 1299,
    comparePrice: 1899,
    stock: 110,
    category: "Smart Home",
    images: [catalogImages.ledStrip],
    rating: 4.7,
    vendor: "EZY Smart Shop",
    badge: "Flash Deal",
    specifications: ["16M colors", "Wi-Fi & remote control", "Syncs to music and scenes"],
    shippingDetails: ["Ships in 24 hours", "COD available", "1-year warranty"]
  },
  {
    id: "prd-7",
    slug: "foldable-laptop-table",
    title: "Foldable Laptop Table",
    description: "Adjustable height/breadth lap desk with cup holder, tablet groove, and anti-slip legs.",
    price: 1799,
    comparePrice: 2599,
    stock: 50,
    category: "Workspace",
    images: [catalogImages.laptopTable],
    rating: 4.3,
    vendor: "EZY Smart Shop",
    specifications: ["Adjustable tilt", "Cup slot + phone groove", "Foldable steel legs"],
    shippingDetails: ["Ships in 48 hours", "Free delivery", "No-cost replacement"]
  },
  {
    id: "prd-8",
    slug: "smart-temperature-water-bottle",
    title: "Smart Temperature Water Bottle",
    description: "Vacuum-insulated bottle with LED temp display, 12-hour insulation, and stainless steel body.",
    price: 1199,
    comparePrice: 1699,
    stock: 95,
    category: "Lifestyle Tech",
    images: [catalogImages.bottle],
    rating: 4.6,
    vendor: "EZY Smart Shop",
    specifications: ["LED temp readout", "500ml double-wall steel", "12-hour insulation"],
    shippingDetails: ["Ships in 24 hours", "COD available", "Easy return"]
  },
  {
    id: "prd-9",
    slug: "selfie-ring-light-with-tripod",
    title: "Selfie Ring Light with Tripod",
    description: "18-inch RGB ring light with 3 color modes, remote, and 61-inch adjustable tripod.",
    price: 1499,
    comparePrice: 2199,
    stock: 75,
    category: "Lifestyle Tech",
    images: [catalogImages.ringLight],
    rating: 4.5,
    vendor: "EZY Smart Shop",
    specifications: ["3 color temperatures", "Bluetooth remote", "61-inch tripod"],
    shippingDetails: ["Ships in 24 hours", "Free delivery", "7-day replacement"]
  },
  {
    id: "prd-10",
    slug: "mini-portable-blender",
    title: "Mini Portable Blender",
    description: "USB-C rechargeable personal blender with 6 stainless blades, 400ml cup, and leakproof lid.",
    price: 1899,
    comparePrice: 2699,
    stock: 70,
    category: "Lifestyle Tech",
    images: [catalogImages.blender],
    rating: 4.4,
    vendor: "EZY Smart Shop",
    badge: "New Arrival",
    specifications: ["6 stainless blades", "USB-C charging", "Leakproof lid"],
    shippingDetails: ["Ships in 48 hours", "COD available", "Warranty support"]
  }
  ,
  {
    id: "prd-11",
    slug: "aroma-diffuser-collection",
    title: "Port-Her Aroma Diffuser",
    description: "Ceramic pebble diffuser with 7-color LED cue, 120ml tank, and whisper-quiet mist for bedside calm.",
    price: 1899,
    comparePrice: 2599,
    stock: 80,
    category: "Wellness & Style",
    images: [catalogImages.diffuser],
    rating: 4.8,
    vendor: "EZY Smart Shop",
    badge: "Self-care pick",
    specifications: ["120ml tank", "Sleep mode mist", "Auto shutoff"],
    shippingDetails: ["Ships in 24 hours", "COD + prepaid", "Free essential oil spritzer"]
  },
  {
    id: "prd-12",
    slug: "handbag-bluetooth-speaker",
    title: "Mini Handbag Bluetooth Speaker",
    description: "Pearl pod speaker with strap clip, 6-hour playback, and sculpted bass suited for handbags and desks.",
    price: 1299,
    comparePrice: 1799,
    stock: 130,
    category: "Wellness & Style",
    images: [catalogImages.handbagSpeaker],
    rating: 4.6,
    vendor: "EZY Smart Shop",
    specifications: ["6-hour battery", "Strap clip + lanyard", "Water-resistant IPX4"],
    shippingDetails: ["Ships in 24 hours", "COD available", "Gift-ready packaging"]
  },
  {
    id: "prd-13",
    slug: "glass-tumbler-bottle",
    title: "Thermal Glass Tumbler",
    description: "Double-walled glass tumbler with bamboo lid, silicone sleeve, and 10-hour retention for teas and smoothies.",
    price: 999,
    comparePrice: 1399,
    stock: 150,
    category: "Wellness & Style",
    images: [catalogImages.tumbler],
    rating: 4.7,
    vendor: "EZY Smart Shop",
    specifications: ["10-hour insulation", "Bamboo lid", "Silicone sleeve"],
    shippingDetails: ["Ships in 24 hours", "COD + prepaid", "Complimentary gift card wrap"]
  }
];

export const testimonials: Testimonial[] = [
  { id: "t1", name: "Aarav S.", location: "Bengaluru", quote: "Fast shipping, premium feel, and the product quality matched the photos exactly." },
  { id: "t2", name: "Ishita R.", location: "Mumbai", quote: "The checkout was smooth and COD made it easy to try the brand for the first order." },
  { id: "t3", name: "Pranav M.", location: "Pune", quote: "The gadget recommendations actually made sense. I ended up buying the light strip too." }
];
